### PR TITLE
Create syntax-highlighting alias shell for bash

### PR DESCRIPTION
**Pull request by MikeRalphson**
This is more extensible later on if more language differences are noticed.

This comes from my port of slate to node (didn't know about your package when I wrote it), https://github.com/mermade/shins - there's some other ideas you might like to pinch there, such as using js-yaml to parse the markdown header, and node-sass for the scss.

### CODE REVIEW

**Review by DoomyTheFroomy — CHANGES_REQUESTED** [review]
Looks okay from my side, except one thing. This PR also contains the changes for #7. So I would recommend to clean this up, or to close PR #7

**Comment by MikeRalphson** [comment]
@DoomyTheFroomy sorry, should never issue a PR from master, should I? Extraneous commit has been expunged. Thanks!

**Review by DoomyTheFroomy — APPROVED** [review]

**Comment by MikeRalphson** [comment]
Non-matching languages between Ruby Rouge and highlight.js as of today seem to be:

```
    ['ceylon','common_lisp','conf','cowscript','erb','factor','io','json-doc','liquid',
'literate_coffeescript','literate_haskell','llvm','make',
    'objective_c','plaintext','praat','properties','racket',
'sass','sed','shell','slim','sml','toml','tulip','viml'];
```

I don't think many would turn up in API docs, apart from the shell/bash one already fixed.

**Comment by jmanek** [comment]
This looks great.  Good to know about which languages do not match.  Would be good to address these at some point, but probably unlikely to see those in docs like this.

**Pull request merged**
